server:
  port: 8080
spring:
  application:
    name: "loan"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "loanApp"
    schema: "public"
    username: "postgres"
    password: "1234"
routes:
  paths:
    createLoan: "/api/v1/application"
    findByTypeLoan: "/api/v1/application/{loanTypeId}"
    findByIdentificationAndLoanType: "/api/v1/application/{identification}/{loanTypeId}"

jwt:
  secret: "4v+9du6Vl3qZrYfLJe6A2P2QYb3B8FgcpzNEkZw1ySA="
  expiration: 360000

config:
  base:
    endpoint:
      client: http://localhost:8081
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
